### ISSUE TITLE
I'm not seeing any list of transaction

### ISSUE THREAD

**Issue by Shaheer5** [adrianhajdin/banking#39]
Hi at the video timestamp @5:08:48.

There is not error or nothing, I think he already have some sort of example transactions but I don't know.
please help

**Comment by bustillos83** [comment]
I am having the same issue i do not get the example transactions

**Comment by basher04** [comment]
I had a similar problem but I was able to solve it by focusing on the getAccount function

**Comment by Shaheer5** [comment]
> I had a similar problem but I was able to solve it by focusing on the getAccount function

Can you share your particular code?

**Comment by basher04** [comment]
export const getAccount = async ({ appwriteItemId }: getAccountProps) => {
  try {
    // get bank from db
    const bank = await getBank({ documentId: appwriteItemId });

    // get account info from plaid
    const accountsResponse = await plaidClient.accountsGet({
      access_token: bank.accessToken,
    });
    const accountData = accountsResponse.data.accounts[0];

    // get transfer transactions from appwrite
    // const transferTransactionsData = await getTransactionsByBankId({
    //   bankId: bank.$id,
    // });

    // const transferTransactions = transferTransactionsData.documents.map(
    //   (transferData: Transaction) => ({
    //     id: transferData.$id,
    //     name: transferData.name!,
    //     amount: transferData.amount!,
    //     date: transferData.$createdAt,
    //     paymentChannel: transferData.channel,
    //     category: transferData.category,
    //     type: transferData.senderBankId === bank.$id ? "debit" : "credit",
    //   })
    // );

    // get institution info from plaid
    const institution = await getInstitution({
      institutionId: accountsResponse.data.item.institution_id!,
    });

    const transactions = await getTransactions({
      accessToken: bank?.accessToken,
    });

    const account = {
      id: accountData.account_id,
      availableBalance: accountData.balances.available!,
      currentBalance: accountData.balances.current!,
      institutionId: institution.institution_id,
      name: accountData.name,
      officialName: accountData.official_name,
      mask: accountData.mask!,
      type: accountData.type as string,
      subtype: accountData.subtype! as string,
      appwriteItemId: bank.$id,
    };

    // sort transactions by date such that the most recent transaction is first
    // const allTransactions = [...transactions, ...transferTransactions].sort(
      const allTransactions = [...transactions].sort(
      (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
    );

    return parseStringify({
      data: account,
      transactions: allTransactions,
    });
  } catch (error) {
    console.error("An error occurred while getting the account:", error);
  }
};

**Comment by Shaheer5** [comment]
Yes I see what you have done, removed ...transferTransactions, and the other thing is that I have updated the page.tsx to
@bustillos83  use the code above given by @basher04  and mine below as well.

`import HeaderBox from '@/components/HeaderBox'
import RecentTransactions from '@/components/RecentTransactions';
import RightSidebar from '@/components/RightSidebar';
import TotalBalanceBox from '@/components/TotalBalanceBox';
import { getAccount, getAccounts } from '@/lib/actions/bank.actions';
import { getLoggedInUser } from '@/lib/actions/user.actions';

const Home = async ({ searchParams: { id, page } }: SearchParamProps) => {
  const currentPage = Number(page as string) || 1;
  const loggedIn = await getLoggedInUser();
  const accounts = await getAccounts({ 
    userId: loggedIn.$id 
  })

  if(!accounts) return;
  
  const accountsData = accounts?.data;
  const appwriteItemId = (id as string) || accountsData[0]?.appwriteItemId;

  const account = await getAccount({ appwriteItemId })

  return (
    <section className="home">
      <div className="home-content">
        <header className="home-header">
          <HeaderBox 
            type="greeting"
            title="Welcome"
            user={loggedIn?.firstName || 'Guest'}
            subtext="Access and manage your account and transactions efficiently."
          />

          <TotalBalanceBox 
            accounts={accountsData}
            totalBanks={accounts?.totalBanks}
            totalCurrentBalance={accounts?.totalCurrentBalance}
          />
        </header>

        <RecentTransactions 
          accounts={accountsData}
          transactions={account?.transactions}
          appwriteItemId={appwriteItemId}
          page={currentPage}
        />
      </div>

      <RightSidebar 
        user={loggedIn}
        transactions={account?.transactions}
        banks={accountsData?.slice(0, 2)}
      />
    </section>
  )
}

export default Home`

**Comment by ucheobi** [comment]
Hey guys, 

The way to solve the problem is to uncomment the "import { getTransactionsByBankId } from "./transaction.actions";" in the bank.actions.ts. Then go to your appwrite dashboard, under the databases->bank_db->transactions. Create two attributes - "senderBankId" and "receiverBankId"(strings). That should solve the problem. You could see in you terminal error log that these attributes are not found. Happy coding!

**Comment by Roise-s** [comment]
I had the same error and i didn't know how to fix it ..... but if u wait ..... it will come it just takes sometime

**Comment by almonteluis** [comment]
I did what was mentioned above to get transactions but still not working. I even checked out the project url in this repo and I don't see transactions either.
